### PR TITLE
Use Julia 1.10 until GAP.jl is compatible with Julia master (v1.12.0-DEV.18, 2024-02-19) again

### PR DESCRIPTION
**Pull request by kamalsaleh**

### CODE REVIEW

**Comment by zickgraf** [comment]
What exactly is the issue with GAP.jl and Julia master? Often Max simply has to trigger some rebuild.

**Comment by kamalsaleh** [comment]
For few days the tests for the jupyter notebooks fail with [this raised error](https://github.com/homalg-project/CategoricalTowers/actions/runs/7939259084):

```
------------------
using CapAndHomalg
------------------

The following 2 direct dependencies failed to precompile:

Base.PkgId(Base.UUID("c863536a-3901-11e9-33e7-d5cd0df7b904"), "GAP")
Failed to precompile GAP [c863536a-3901-11e9-33e7-d5cd0df7b904] to "/home/gap/.julia/compiled/v1.12/GAP/jl_nkeqRI".

ERROR: LoadError: This platform or julia version is currently not supported by GAP:
x86_64-linux-gnu-libgfortran5-cxx11-libstdcxx30-julia_version+1.12.0
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ ~/.julia/packages/GAP/0puCA/src/GAP.jl:25
 [3] include
   @ ./Base.jl:556 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2484
 [5] top-level scope
   @ stdin:4
in expression starting at /home/gap/.julia/packages/GAP/0puCA/src/GAP.jl:1
in expression starting at stdin:4
Base.PkgId(Base.UUID("c4774649-1891-41ea-a883-87141804c57c"), "CapAndHomalg")
```

I didn't try to debug this error, but I know that tests pass with Julia 1.10.

@fingolfin I am not sure if the oscar-system team is aware of this issue with the current Julia master.

**Comment by fingolfin** [comment]
Whenever they create a new branch and update the main version on the Julia master branch, a bunch of things need to happen; specifically, many "JLLs" need to updated to also include that new Julia version.

Nobody has done this so far. It'll come eventually, though, we have it on our radar.

**Comment by kamalsaleh** [comment]
Thank you for the clarification.

**Pull request merged**
